	SELECT
		DB_NAME() database_name,
		DB_ID() database_id,
		ix.object_id,
		OBJECT_NAME(ix.object_id) obj_name,
		OBJECT_SCHEMA_NAME(ix.object_id) schema_name,
		ix.name index_name,
		ustats.index_id,
		op_stat.row_lock_count,
		op_stat.row_lock_wait_count,
		op_stat.index_lock_promotion_count,
		op_stat.page_lock_wait_count,
		ustats.user_seeks,
		ustats.user_lookups,
		ustats.user_updates,
		ustats.user_scans,
		op_stat.row_lock_wait_in_ms + op_stat.page_lock_wait_in_ms lock_wait_in_ms,
		op_stat.page_latch_wait_in_ms + op_stat.page_io_latch_wait_in_ms + op_stat.tree_page_io_latch_wait_in_ms + op_stat.tree_page_latch_wait_in_ms latch_wait_in_ms,
		op_stat.leaf_insert_count + op_stat.leaf_delete_count + op_stat.leaf_update_count leaf_modifications_count,
		op_stat.nonleaf_insert_count + op_stat.nonleaf_delete_count + op_stat.nonleaf_update_count nonleaf_modifications_count,
		op_stat.nonleaf_insert_count,
		op_stat.nonleaf_delete_count,
		op_stat.nonleaf_update_count,
		op_stat.leaf_allocation_count,
		op_stat.nonleaf_allocation_count,
		op_stat.row_lock_wait_in_ms,
		op_stat.page_lock_wait_in_ms,
		op_stat.page_latch_wait_in_ms,
		op_stat.page_io_latch_wait_in_ms,
		op_stat.tree_page_io_latch_wait_in_ms,
		op_stat.tree_page_latch_wait_in_ms,
		op_stat.lob_fetch_in_bytes,
		op_stat.leaf_insert_count,
		op_stat.leaf_delete_count,
		op_stat.leaf_update_count,
		STATS_DATE(ix.object_id, ix.index_id) statistic_date,
		ustats.last_user_seek,
		ustats.last_user_scan,
		ustats.last_user_lookup,
		ustats.last_user_update
	FROM sys.dm_db_index_usage_stats ustats
		INNER JOIN sys.indexes ix ON ix.object_id = ustats.object_id
														 AND ix.index_id = ustats.index_id
		CROSS APPLY sys.dm_db_index_operational_stats(ustats.database_id, ustats.object_id, ustats.index_id, NULL) op_stat
	WHERE ustats.database_id = DB_ID()